// Do not edit this file
class Node implements Comparable<Node>
        
 {Car info;
  Node left,right;

    public Node(Car info, Node left, Node right) {
        this.info = info;
        this.left = left;
        this.right = right;
    }
 
  Node(Car x)
   {this(x,null,null);
   }

    @Override
    public int compareTo(Node o) {
        return Integer.compare( info.price,o.info.price);
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 }

